import os
import time
from datetime import datetime
from io import BytesIO

import cv2
import gdown
import numpy as np
import streamlit as st
import tensorflow as tf
from PIL import Image
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


st.set_page_config(
    page_title="AI Chest X-ray Diagnosis",
    page_icon="🩺",
    layout="wide"
)

st.markdown("""
<style>
.stApp{background-color:#0E1117;}
section[data-testid="stSidebar"]{background-color:#111827;}
section[data-testid="stSidebar"] *{color:white;}

div[data-testid="stMetric"]{
    background:#1E293B;
    border-radius:15px;
    padding:20px;
    border:1px solid #334155;
}

.stButton>button,
.stDownloadButton>button{
    background:#2563EB;
    color:white;
    border-radius:10px;
    font-weight:bold;
    border:none;
    width:100%;
}

.stProgress > div > div > div > div{background:#2563EB;}

.footer{
    text-align:center;
    color:#94A3B8;
    font-size:14px;
}
</style>
""", unsafe_allow_html=True)


MODEL_URL = "https://drive.google.com/uc?id=1UBeJIDa_Rc8C4Eqra3c2jAScCNv484DU"
MODEL_PATH = "chest_xray_cnn_model.keras"
IMAGE_SIZE = (224, 224)
LAST_CONV_LAYER_NAME = "conv2d_2"


@st.cache_resource
def load_trained_model():
    if not os.path.exists(MODEL_PATH):
        gdown.download(MODEL_URL, MODEL_PATH, quiet=False)

    return tf.keras.models.load_model(MODEL_PATH)


def preprocess_uploaded_image(image):
    image_np = np.array(image.convert("RGB"))

    gray = cv2.cvtColor(image_np, cv2.COLOR_RGB2GRAY)
    resized = cv2.resize(gray, IMAGE_SIZE)
    normalized = resized.astype(np.float32) / 255.0

    input_image = normalized.reshape(1, 224, 224, 1)

    return image_np, input_image


def generate_gradcam_overlay(model, original_image, input_image):
    last_conv_layer = model.get_layer(LAST_CONV_LAYER_NAME)

    conv_model = tf.keras.models.Model(
        inputs=model.inputs,
        outputs=last_conv_layer.output
    )

    classifier_input = tf.keras.Input(shape=last_conv_layer.output.shape[1:])

    x = classifier_input
    start = False

    for layer in model.layers:
        if layer.name == LAST_CONV_LAYER_NAME:
            start = True
            continue

        if start:
            x = layer(x)

    classifier_model = tf.keras.models.Model(classifier_input, x)

    input_tensor = tf.convert_to_tensor(input_image, dtype=tf.float32)

    with tf.GradientTape() as tape:
        conv_outputs = conv_model(input_tensor)
        tape.watch(conv_outputs)
        predictions = classifier_model(conv_outputs)
        loss = predictions[:, 0]

    gradients = tape.gradient(loss, conv_outputs)
    pooled_gradients = tf.reduce_mean(gradients, axis=(0, 1, 2))

    conv_outputs = conv_outputs[0]

    heatmap = conv_outputs @ pooled_gradients[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)
    heatmap = tf.maximum(heatmap, 0)

    max_value = tf.reduce_max(heatmap)

    if max_value != 0:
        heatmap = heatmap / max_value

    heatmap = heatmap.numpy()
    heatmap = cv2.resize(heatmap, IMAGE_SIZE)

    heatmap_uint8 = np.uint8(255 * heatmap)

    colored_heatmap = cv2.applyColorMap(
        heatmap_uint8,
        cv2.COLORMAP_JET
    )

    colored_heatmap = cv2.cvtColor(
        colored_heatmap,
        cv2.COLOR_BGR2RGB
    )

    original_resized = cv2.resize(original_image, IMAGE_SIZE)

    overlay = cv2.addWeighted(
        original_resized,
        0.6,
        colored_heatmap,
        0.4,
        0
    )

    return overlay, predictions


def generate_pdf_report(prediction, confidence, raw_probability, gradcam_path):
    buffer = BytesIO()

    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawString(50, height - 50, "AI Chest X-ray Diagnosis Report")

    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, height - 90, f"Prediction: {prediction}")
    pdf.drawString(50, height - 115, f"Confidence: {confidence:.2f}%")
    pdf.drawString(50, height - 140, f"Raw Pneumonia Probability: {raw_probability}")
    pdf.drawString(
        50,
        height - 165,
        f"Generated At: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, height - 210, "Grad-CAM Explanation")

    if os.path.exists(gradcam_path):
        pdf.drawImage(
            gradcam_path,
            50,
            height - 560,
            width=420,
            height=300,
            preserveAspectRatio=True,
            mask="auto"
        )

    pdf.setFont("Helvetica", 10)
    pdf.drawString(
        50,
        80,
        "Disclaimer: This report is generated by an AI model for educational/project purposes only."
    )
    pdf.drawString(
        50,
        65,
        "It should not be used as a substitute for professional medical diagnosis."
    )

    pdf.save()
    buffer.seek(0)

    return buffer


st.markdown("""
# 🩺 AI Chest X-ray Diagnosis System

### Explainable AI for Pneumonia Detection using Deep Learning

---
""")

st.write(
    "Upload a chest X-ray image and get an AI prediction with Grad-CAM visual explanation."
)


with st.sidebar:
    st.header("📌 Project Info")
    st.write("**Model:** Custom CNN")
    st.write("**Validation Accuracy:** 94%")
    st.write("**Classes:** Normal / Pneumonia")
    st.write("**Explainability:** Grad-CAM")
    st.write("**Inference:** TensorFlow")
    st.write("**Frontend:** Streamlit")
    st.write("**Backend Code:** FastAPI included in repository")
    st.write("**Author:** Suhani Gupta")
    st.warning("Educational project only. Not for real medical diagnosis.")

    st.markdown("---")
    st.success("Model Status: Ready")

    st.caption("""
Dataset:
Chest X-ray Pneumonia Dataset

Frameworks:
TensorFlow
Streamlit
OpenCV
Grad-CAM
ReportLab
""")


uploaded_file = st.file_uploader(
    "Upload Chest X-ray Image",
    type=["jpg", "jpeg", "png"]
)


if uploaded_file is None:
    st.info("Please upload a chest X-ray image to begin.")
    st.stop()


image = Image.open(uploaded_file)

left_col, right_col = st.columns([1.1, 1])


with left_col:
    st.subheader("Uploaded X-ray")
    st.image(
        image,
        caption="Uploaded Chest X-ray",
        use_container_width=True
    )


with st.spinner("🧠 Running CNN inference and generating Grad-CAM..."):
    model = load_trained_model()

    start_time = time.time()

    original_image, input_image = preprocess_uploaded_image(image)

    overlay_image, predictions = generate_gradcam_overlay(
        model,
        original_image,
        input_image
    )

    processing_time = time.time() - start_time


raw_probability = float(predictions.numpy()[0][0])

if raw_probability > 0.5:
    prediction = "Pneumonia"
    confidence = raw_probability * 100
else:
    prediction = "Normal"
    confidence = (1 - raw_probability) * 100

confidence = round(confidence, 2)
raw_probability = round(raw_probability, 4)

gradcam_path = "gradcam_overlay.jpg"
Image.fromarray(overlay_image).save(gradcam_path)


with right_col:
    st.subheader("Diagnosis Result")

    if prediction == "Pneumonia":
        st.markdown("""
        <div style="
            background:#3b0d0d;
            border-left:8px solid #ef4444;
            padding:25px;
            border-radius:15px;
            color:white;
        ">
            <h2>🔴 Pneumonia Detected</h2>
            <p>The AI model found patterns consistent with pneumonia.</p>
        </div>
        """, unsafe_allow_html=True)

    else:
        st.markdown("""
        <div style="
            background:#052e16;
            border-left:8px solid #22c55e;
            padding:25px;
            border-radius:15px;
            color:white;
        ">
            <h2>🟢 Normal Chest X-ray</h2>
            <p>No pneumonia patterns detected by the AI model.</p>
        </div>
        """, unsafe_allow_html=True)

    st.metric(
        label="AI Confidence",
        value=f"{confidence:.2f}%"
    )

    st.progress(confidence / 100)

    st.metric(
        "Processing Time",
        f"{processing_time:.2f} sec"
    )

    st.caption(
        f"The model is **{confidence:.2f}% confident** that this image belongs to the **{prediction}** class."
    )

    st.caption(f"Raw pneumonia probability: {raw_probability}")


st.divider()

st.subheader("Grad-CAM Explainability")

if os.path.exists(gradcam_path):
    gradcam_image = Image.open(gradcam_path)

    st.image(
        gradcam_image,
        caption="Grad-CAM Overlay: highlighted regions influenced the prediction",
        use_container_width=True
    )

    col_a, col_b = st.columns(2)

    with col_a:
        pdf_report = generate_pdf_report(
            prediction,
            confidence,
            raw_probability,
            gradcam_path
        )

        st.download_button(
            label="📄 Download PDF Report",
            data=pdf_report,
            file_name="AI_Chest_Xray_Report.pdf",
            mime="application/pdf"
        )

    with col_b:
        with open(gradcam_path, "rb") as file:
            st.download_button(
                label="🖼️ Download Grad-CAM Image",
                data=file,
                file_name="gradcam_overlay.jpg",
                mime="image/jpeg"
            )

else:
    st.warning("Grad-CAM image was generated but could not be found.")


st.divider()

st.markdown("""
### How it works
1. The uploaded X-ray is preprocessed using OpenCV.
2. A CNN predicts whether the image is Normal or Pneumonia.
3. Grad-CAM highlights the regions that influenced the prediction.
4. TensorFlow performs inference and Streamlit displays the result.
""")

st.markdown("""
<div class="footer">
Built with TensorFlow • OpenCV • Streamlit • Grad-CAM • ReportLab<br>
© 2026 Suhani Gupta
</div>
""", unsafe_allow_html=True)