from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from io import BytesIO

import os
import time 
from datetime import datetime

import requests
import streamlit as st
from PIL import Image


st.set_page_config(
    page_title="AI Chest X-ray Diagnosis",
    page_icon="🩺",
    layout="wide"
)

st.markdown("""
<style>
.stApp{
    background-color:#0E1117;
}

section[data-testid="stSidebar"]{
    background-color:#111827;
}

section[data-testid="stSidebar"] *{
    color:white;
}

div[data-testid="stMetric"]{
    background:#1E293B;
    border-radius:15px;
    padding:20px;
    border:1px solid #334155;
}

.stButton>button,
.stDownloadButton>button{
    background:#2563EB;
    color:white;
    border-radius:10px;
    font-weight:bold;
    border:none;
    width:100%;
}

.stProgress > div > div > div > div{
    background:#2563EB;
}

.footer{
    text-align:center;
    color:#94A3B8;
    font-size:14px;
}
</style>
""", unsafe_allow_html=True)


BACKEND_URL = "http://127.0.0.1:8000/predict"

def generate_pdf_report(prediction, confidence, raw_probability, gradcam_path):
    buffer = BytesIO()

    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawString(50, height - 50, "AI Chest X-ray Diagnosis Report")

    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, height - 90, f"Prediction: {prediction}")
    pdf.drawString(50, height - 115, f"Confidence: {confidence:.2f}%")
    pdf.drawString(50, height - 140, f"Raw Pneumonia Probability: {raw_probability}")
    pdf.drawString(
        50,
        height - 165,
        f"Generated At: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )

    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, height - 210, "Grad-CAM Explanation")

    if os.path.exists(gradcam_path):
        pdf.drawImage(
            gradcam_path,
            50,
            height - 560,
            width=420,
            height=300,
            preserveAspectRatio=True,
            mask="auto"
        )

    pdf.setFont("Helvetica", 10)
    pdf.drawString(
        50,
        80,
        "Disclaimer: This report is generated by an AI model for educational/project purposes only."
    )
    pdf.drawString(
        50,
        65,
        "It should not be used as a substitute for professional medical diagnosis."
    )

    pdf.save()

    buffer.seek(0)
    return buffer


st.markdown("""
# 🩺 AI Chest X-ray Diagnosis System

### Explainable AI for Pneumonia Detection using Deep Learning

---
""")

st.write(
    "Upload a chest X-ray image and get an AI prediction with Grad-CAM visual explanation."
)


with st.sidebar:
    st.header("📌 Project Info")
    st.write("**Model:** Custom CNN")
    st.write("**Validation Accuracy:** 94%")
    st.write("**Classes:** Normal / Pneumonia")
    st.write("**Explainability:** Grad-CAM")
    st.write("**Backend:** FastAPI")
    st.write("**Frontend:** Streamlit")
    st.write("**Author:** Suhani Gupta")
    st.warning("Educational project only. Not for real medical diagnosis.")

    st.markdown("---")
    st.success("Model Status: Ready")

    st.caption("""
Dataset:
Chest X-ray Pneumonia Dataset

Frameworks:
TensorFlow
FastAPI
Streamlit
OpenCV
""")


uploaded_file = st.file_uploader(
    "Upload Chest X-ray Image",
    type=["jpg", "jpeg", "png"]
)


if uploaded_file is None:
    st.info("Please upload a chest X-ray image to begin.")
    st.stop()


image = Image.open(uploaded_file)

left_col, right_col = st.columns([1.1, 1])


with left_col:
    st.subheader("Uploaded X-ray")
    st.image(
        image,
        caption="Uploaded Chest X-ray",
        use_container_width=True
    )

start_time = time.time()
with st.spinner("🧠 Running CNN inference and generating Grad-CAM..."):
    files = {
        "file": (
            uploaded_file.name,
            uploaded_file.getvalue(),
            uploaded_file.type
        )
    }

    response = requests.post(BACKEND_URL, files=files)
    end_time = time.time()
    processing_time = end_time - start_time


if response.status_code != 200:
    st.error("Prediction failed")
    st.write(response.text)
    st.stop()


result = response.json()

prediction = result["prediction"]
confidence = result["confidence"]
raw_probability = result["raw_probability"]
gradcam_path = result["gradcam_path"]


with right_col:
    st.subheader("Diagnosis Result")

    if prediction == "Pneumonia":
        st.markdown("""
        <div style="
            background:#3b0d0d;
            border-left:8px solid #ef4444;
            padding:25px;
            border-radius:15px;
            color:white;
        ">
            <h2>🔴 Pneumonia Detected</h2>
            <p>The AI model found patterns consistent with pneumonia.</p>
        </div>
        """, unsafe_allow_html=True)

    else:
        st.markdown("""
        <div style="
            background:#052e16;
            border-left:8px solid #22c55e;
            padding:25px;
            border-radius:15px;
            color:white;
        ">
            <h2>🟢 Normal Chest X-ray</h2>
            <p>No pneumonia patterns detected by the AI model.</p>
        </div>
        """, unsafe_allow_html=True)

    st.metric(
        label="AI Confidence",
        value=f"{confidence:.2f}%"
    )

    st.progress(confidence / 100)

    st.metric(
    "Processing Time",
    f"{processing_time:.2f} sec"
)

    st.caption(
        f"The model is **{confidence:.2f}% confident** that this image belongs to the **{prediction}** class."
    )

    st.caption(f"Raw pneumonia probability: {raw_probability}")


st.divider()

st.subheader("Grad-CAM Explainability")

if os.path.exists(gradcam_path):
    gradcam_image = Image.open(gradcam_path)

    st.image(
        gradcam_image,
        caption="Grad-CAM Overlay: highlighted regions influenced the prediction",
        use_container_width=True
    )

    report_text = f"""
AI Chest X-ray Diagnosis Report

Prediction: {prediction}
Confidence: {confidence}%
Raw Pneumonia Probability: {raw_probability}

Generated At: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

Project:
AI Chest X-ray Diagnosis System using CNN and Grad-CAM

Disclaimer:
This report is generated by an AI model for educational/project purposes only.
It should not be used as a substitute for professional medical diagnosis.
"""

    col_a, col_b = st.columns(2)

    with col_a:
        pdf_report = generate_pdf_report(
            prediction,
            confidence,
            raw_probability,
            gradcam_path
        )

        st.download_button(
            label="📄 Download PDF Report",
            data=pdf_report,
            file_name="AI_Chest_Xray_Report.pdf",
            mime="application/pdf"
        )

    with col_b:
        with open(gradcam_path, "rb") as file:
            st.download_button(
                label="🖼️ Download Grad-CAM Image",
                data=file,
                file_name="gradcam_overlay.jpg",
                mime="image/jpeg"
            )

else:
    st.warning("Grad-CAM image was generated but could not be found.")


st.divider()

st.markdown("""
### How it works
1. The uploaded X-ray is preprocessed using OpenCV.
2. A CNN predicts whether the image is Normal or Pneumonia.
3. Grad-CAM highlights the regions that influenced the prediction.
4. FastAPI handles prediction, and Streamlit displays the result.
""")

st.markdown("""
<div class="footer">
Built with TensorFlow • OpenCV • FastAPI • Streamlit • Grad-CAM<br>
© 2026 Suhani Gupta
</div>
""", unsafe_allow_html=True)